### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by bhargavjoshi** [kaienkira/acme-client-quick#1]
Can we have this in a docker container for this process?

There are many cases where I need a certificate, but I have different apps and languages I use, for that I would not like to install this on a docker container and get the certificate and then stop the container. 

Then again when I want to renew the certificates it would be great if I could just repeat the process. 

Best,
Bhargav Joshi

**Comment by kaienkira** [comment]
This tool is self contained. 
It will keep all generated files in  current working directory, so if you don't need it, just delete the whole dir.
It *will not * change any of your system config, even your nginx config (because it use a self contained nginx service).

If you need 2 or more copy, just copy the whole dir. That's ok.
